name: Deploy to GitHub Pages via angular-cli-ghpages

on: [ push ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Prepare and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
          npm install
          npm run write-env
          npm run ng -- deploy --base-href=/tailwind-weather-app/ --name="SebastianPost96" --email="sebastianpost@online.de" --no-silent
